name: gv-sequence-tools
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - hmmer=3.4
  - mafft=7.526
  - blast=2.17
  - cd-hit=4.8.1
  - pip
  - pip:
      - -r requirements-integration.txt
